# 02장 넘파이(Numpy)

## 01) 넘파이 소개

### 넘파이 소개

In [1]:
!pip install numpy

In [2]:
import numpy as np
data = [1,2,3]
arr = np.array(data)
print(arr, type(arr))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
data = [1,2,3]

result = []
for i in data:
    result.append(i * 10)
print(result)

[10, 20, 30]


In [4]:
import numpy as np
arr = np.array([1,2,3])
result = arr * 10
print(result)

[10 20 30]


In [7]:
data2d = [
    [1,2,3],
    [4,5,6,],
    [7,8,9]
]
print(data2d[0]) # list 출력

[1, 2, 3]


In [8]:
import numpy as np

data2d = [
    [1,2,3],
    [4,5,6,],
    [7,8,9]
]
arr = np.array(data2d)
print(arr[:, 0]) # ndarray 출력

[1 4 7]


In [20]:
print(arr)
arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ndarray
ndarray객체는 리스트와 달리 데이터와 데이터 사이에 콤마 구분 기호 없이 출력

In [17]:
data1 = [1,2,3,4]
arr1 = np.array(data1)
print(arr1, type(arr1))

[1 2 3 4] <class 'numpy.ndarray'>


In [24]:
data2 = [
    [1,2],
    [3,4]
]

arr2 = np.array(data2)
print(arr)
print(type(arr2))
print(type(arr2[0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

(2, 2)
2
int32


In [27]:
print(arr1.shape)

(4,)


In [28]:
data = [
    [1],
    [2],
    [3],
    [4]    
]
c = np.array(data)
print( c.shape )

(4, 1)


In [29]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [1]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
size = (3, 4)
np.zeros(size)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.arange(5)

In [ ]:
np.arange(1,5)

In [ ]:
np.arange(1,5,2)

In [3]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2,3)
ndarr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(ndarr2)

## 03) 데이터 타입

In [6]:
arr = np.array([1,2,3], dtype=np.uint8)
print(arr)
print(arr.dtype)
print(arr.dtype.kind)       # data type 종류
print(arr.dtype.alignment)
arr = arr.astype('int8') # data type 변경
print(arr.dtype)

[1 2 3]
uint8
u
1
int8


In [7]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b) # int8

[  0 255]
[ 0 -1]


In [8]:
a16 = np.array( [1.333333], dtype=np.float16)
a32 = np.array( [1.333333], dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [9]:
print(np.nan,  type(np.nan))
print(np.inf,  type(np.inf))
print(-np.inf,  type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [10]:
arr = np.array([-1, 2, -3])
print(arr/0)

[-inf  inf -inf]


In [11]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 4) 인덱싱과 슬라이싱

In [ ]:
arr = np.arange(4)
arr
arr[0]

In [ ]:
arr = np.arange(4).reshape(2,2)
print(arr[0])
print(arr[0][0])
print(arr[0, 0])

In [ ]:
# arr[0][0] 과 arr[0,0]의 처리 속도
# timeit 뒤에 나오는 코드를 1000만번을 7번 반복실행하고 걸린 시간의 평균을 반환

a = np.arange(10000).reshape(100,100)
%timeit a[0,50]

In [ ]:
a=np.arange(10000).reshape(100, 100)
%timeit a[0][50]

In [15]:
arr = np.arange(4)
print(arr[:2])

[0 1]


In [14]:
arr = np.arange(4)
target = [ 0, 2 ]
print(arr[ target ])

[0 2]


In [13]:
arr = np.arange(5)
arr[[0,2]]

array([0, 2])

In [12]:
a=np.arange(16).reshape(4, 4)
a[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [16]:
arr = np.arange(20).reshape(4, 5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
arr = np.arange(20).reshape(4, 5)
result = []
for row in arr:
    row_01 = [row[0], row[1]]
    result.append(row_01)

result    

[[0, 1], [5, 6], [10, 11], [15, 16]]

In [19]:
arr[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [20]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
print(arr[ 1:4, 2:5])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [22]:
print(arr[1:, 2:])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## 05) 브로드캐스팅 

In [23]:
import numpy as np
a = np.array( [ 1, 2, 3] )
b = np.array( [ 2, 3, 4] )
print( a + b )
print( a * b )
print( a % b )

[3 5 7]
[ 2  6 12]
[1 2 3]


In [24]:
# 스칼라(sclar) 연산은 전체 데이터에 확장 적용
print(a + 3)

[4 5 6]


In [25]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [ ]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

In [ ]:
avg = (arr_high * 3 + arr_low * 2)
avg

In [ ]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)
arr

In [ ]:
arr[0]*3 + arr[1]*2

In [26]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)

weight = np.array( [ 3, 2 ] ).reshape(2, 1)
print((weight * arr).sum(axis=0))

[458100 459400 459700 467100 458700]


## 06) 조건 연산

In [ ]:
arr = np.array([10, 20, 30])
print(arr > 10)

In [ ]:
arr = np.array([10,20,30])
cond = [False, True, True]
arr[cond]

In [ ]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

In [ ]:
# any() - 하나라도 참일 경우 참을 반환
# all() - 모두 참일 경우 참을 반환
print(cond.all())
print(cond.any())

In [ ]:
# 파이썬의 기본 논리 연산자로 and, or, not이 있었다면 넘파이에서는 &, |, ~을 사용
arr = np.array([10, 20, 30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[ cond0 & cond1 ])

In [ ]:
arr = np.array([10, 20, 30])
print(arr[ (arr > 10) & (arr < 30) ])

In [ ]:
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = 1
arr[~cond] = 0
print(arr)

In [ ]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0)
print(arr)

In [ ]:
# 만약 10보다 크다면 10을 더하고 그렇지 않다면 10을 빼고 싶은 경우
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] -10

arr

In [ ]:
# where 를 사용하면 더욱 간단히 표현
import numpy as np

arr = np.array([10, 20, 30])
np.where(arr > 10, arr + 10, arr - 10)

In [ ]:
# 주가가 85000 이하로 떨어진 날은 며칠일까요?
lge = np.array([93000, 82400, 99100, 81000, 72300])
np.where(lge <= 85000, 1, 0).sum()

In [ ]:
result = lge[lge <= 85000]
len(result)

## 07) 함수와 메서드

In [ ]:
# sum 메서드
arr = np.arange(8).reshape(4,2)
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))


3

In [ ]:
arr.sum(axis=0)

In [ ]:
# randint : 입력된 범위에서 임의의 정수를 반환
print(np.random.randint(46, size=5))
print(np.random.randint(46, size=(2,5)))


In [ ]:
# linspce 함수 : 첫번째로 시작값, 두번째는 종료값, 세번째는 분할 지점의 수
x = np.linspace(0,10,3)
x

In [28]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.vstack([a, b])
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [27]:
a = np.arange(4)
b = np.arange(4, 8)
c = np.hstack([a, b])
print(c)

[0 1 2 3 4 5 6 7]
