# NumPy(Numerical Python)

* 수학 및 과학적 연산을 쉽고 빠르게 지원
* 다차원 <font color = 'blue'>행열</font>(Array/Matrix)을 효과적으로 처리
* 일반적으로 <font color = 'red'>같은 데이터 타입 값</font>으로 구성
* https://numpy.org

In [1]:
import warnings
warnings.filterwarnings('ignore')

# I. NumPy Package import ~ as

In [2]:
import numpy as np 

* Version Check

In [3]:
np.__version__

'1.21.6'

# II. Array 생성

* Python <font color = 'blue'>List 구조</font>를 사용

>## 1) Scalar - 0D Array - Rank0 Tensor

In [4]:
a0 = np.array(9)

In [5]:
print(a0)

9


>## 2) Vector - 1D Array - Rank1 Tensor

In [6]:
a1 = np.array([1, 3, 5, 7, 9])

In [7]:
print(a1)

[1 3 5 7 9]


In [8]:
a1[2]

5

In [9]:
a1[1:3]

array([3, 5])

>## 3) Matrix - 2D Array - Rank2 Tensor

In [10]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [11]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* a2[행]

In [12]:
a2[1]

array([4, 5, 6])

* a2[행, 열]

In [13]:
a2[1, 1]

5

* a2[<font color = 'blue'>행</font>, 열]

In [14]:
a2[:, 1]

array([2, 5, 8])

>## 4) Array - 3D Array - Rank3 Tensor

In [15]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])

In [16]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* a3[축]

In [17]:
a3[1]

array([[5, 6],
       [7, 8]])

* a3[축, 행]

In [18]:
a3[1, 1]

array([7, 8])

* a3[축, 행, 열]

In [19]:
a3[1, 1, 1]

8

* a3[<font color = 'blue'>축</font>, 행, 열]

In [20]:
a3[:, 0, 0]

array([1, 5, 9])

* a3[<font color = 'blue'>축</font>, <font color = 'blue'>행</font>, 열]

In [21]:
a3[:, :, 0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

# III. AR.shape and AR.reshape( )

In [22]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [23]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


>## 1) .shape

* 행렬 크기

In [24]:
AR.shape 

(12,)

* 행렬 차원

In [25]:
AR.ndim

1

* 행렬 원소 개수

In [26]:
AR.size

12

>## 2) .reshape(3, 4)

* <font color = 'blue'>.reshape(</font>행, 열<font color = 'blue'>)</font>

In [27]:
AR2 = AR.reshape(3, 4)

In [28]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* 행렬 크기

In [29]:
AR2.shape 

(3, 4)

* 행렬 차원

In [30]:
AR2.ndim

2

* 행렬 원소 개수

In [31]:
AR2.size

12

>## 3) .reshape(3, 2, 2)

* .reshape(<font color = 'red'>축</font>, 행, 열)

In [32]:
AR3 = AR.reshape(3, 2, 2)

In [33]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* 행렬의 크기

In [34]:
AR3.shape

(3, 2, 2)

* 행렬의 원소 개수

In [35]:
AR3.size

12

* 행렬의 차원

In [36]:
AR3.ndim

3

>## 4) .reshape(<font color = 'red'>-1</font>, 1)

* .reshape(<font color = 'red'>12</font>, 1)

In [37]:
AR.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

   * .reshape(1, <font color = 'blue'>12</font>)

In [38]:
AR2.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [39]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* <font color = 'blue'>.flatten( )

In [41]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IV. 범위 지정(arange) 함수

>## 1) 연속된 10개 값 생성

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 2) 1부터 9까지 <font color = 'blue'>1간격</font>으로 생성

In [43]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 3) 1부터 9까지 <font color = 'red'>2간격</font>으로 생성

In [44]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

>## 4) Array 생성 후 <font color = 'blue'>.reshape( )</font> 적용

In [45]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# V. 특별한 형태의 Array 생성

>## 1) 0과 1로만 구성된 Array

* <font color = 'blue'>0으로만 구성

In [46]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* <font color = 'blue'>1로만 구성

In [48]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 산술연산을 적용하여 <font color = 'blue'>'9'로만 구성</font>된 행렬 생성

In [50]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

>## 2) 3 x 3 <font color = 'red'>단위행렬

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

>## 3) 난수 Array 생성

* <font color = 'blue'>실수</font> 난수 생성
 - (축, 행, 열)

In [52]:
np.random.rand(3, 2, 2)

array([[[0.41565752, 0.78157159],
        [0.04832343, 0.72729321]],

       [[0.02084472, 0.98479467],
        [0.56655433, 0.78468959]],

       [[0.10925509, 0.40887507],
        [0.780092  , 0.48542899]]])

* 주어진 <font color = 'blue'>정수</font> 범위에서 난수 생성
 - 1 ~ 44 사이
 - 복원 추출
 - (행, 열)

In [53]:
np.random.randint(1, 45, size = (5, 6))

array([[ 3, 27,  4,  4, 15, 42],
       [43, 36, 33, 37, 28, 12],
       [16, 27,  8, 22, 39, 37],
       [32, 28,  5, 34, 12, 27],
       [27, 24, 34, 18, 22, 16]])

* np.random.<font color = 'red'>seed( )</font>
 - 의사난수(Pseudo Random Number) 생성 초기값 지정
 - <font color = 'red'>항상 같은 난수 생성</font>
 - 비복원 추출

In [54]:
np.random.seed(2045)

np.random.choice(np.arange(1, 46), size = (5 ,6), replace = False)

array([[ 7, 32,  6, 41,  4, 34],
       [30, 28, 16,  5, 38, 33],
       [31, 13, 25, 23, 43, 12],
       [45,  8, 29, 22, 18,  9],
       [21, 20, 40,  2, 37, 39]])

* <font color = 'blue'>정규분포</font>(Normal Distribution)
 - 평균 : 0.0
 - 분산 : 1.0

In [55]:
np.random.normal(0.0, 1.0, (3, 4))

array([[ 0.71947166,  1.80057273,  0.63316945,  0.51061538],
       [-1.21195057, -0.59379034, -0.3425329 , -0.27237291],
       [ 0.49302831,  1.69163948, -1.51220426,  2.21618257]])

* <font color = 'blue'>단일분포</font>(Uniform Distribution)
 - 1.0 이상 ~ 6.0 미만

In [56]:
np.random.uniform(1.0, 6.0, (3, 4))

array([[5.65951144, 5.29274022, 3.47886212, 4.94995432],
       [3.80139197, 4.60368368, 1.89916098, 3.48651253],
       [5.00192081, 1.53362512, 1.88355585, 5.17922231]])

* <font color = 'blue'>shuffle( )</font>
 - 원소 섞기

In [57]:
TA = np.arange(1, 10)

TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.random.shuffle(TA)

TA

array([8, 6, 3, 5, 4, 9, 2, 7, 1])

# VI. Array 연산

In [59]:
A1 = np.array([1, 3, 5, 7, 9])

A2 = np.array([10, 30, 50, 70, 90])

A3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

>## 1) 기본 연산

* 각각의 <font color = 'blue'>행과 열의 값을 매칭</font>하여 연산 수행

In [60]:
A1 + A2

array([11, 33, 55, 77, 99])

In [61]:
A2 - A1

array([ 9, 27, 45, 63, 81])

In [62]:
A1 * A2

array([ 10,  90, 250, 490, 810])

In [63]:
A2 / A1

array([10., 10., 10., 10., 10.])

In [64]:
A1 * 3

array([ 3,  9, 15, 21, 27])

In [65]:
A1 ** 2

array([ 1,  9, 25, 49, 81])

>## 2) 통계량 연산

* 총합

In [66]:
A1.sum()

25

* 평균

In [67]:
A2.mean()

50.0

* 분산
 - 'ddof = 0'

In [68]:
A2.var()

800.0

* 표준 편차
 - 'ddof = 0'

In [69]:
A2.std()

28.284271247461902

* 최소값

In [70]:
A2.min()

10

> * A3 전체 최소값

  

In [71]:
A3.min()

1

> * A3 각 열의 최소값

In [72]:
A3.min(axis = 0)

array([1, 2, 3])

> * A3 각 행의 최소값

In [73]:
A3.min(axis = 1)

array([1, 4, 7])

In [74]:
A3.min(axis = 1, keepdims = True)

array([[1],
       [4],
       [7]])

* 최대값

In [75]:
A2.max()

90

> * A3 전체 최대값

In [76]:
A3.max()

9

> * A3 각 열의 최대값

In [77]:
A3.max(axis = 0)

array([7, 8, 9])

> * A3 각 행의 최대값

In [78]:
A3.max(axis = 1)

array([3, 6, 9])

In [79]:
A3.max(axis = 1, keepdims = True)

array([[3],
       [6],
       [9]])

* 누적(Cumulative)합

In [80]:
A1.cumsum()

array([ 1,  4,  9, 16, 25])

* 누적(Cumulative)곱

In [81]:
A1.cumprod()

array([  1,   3,  15, 105, 945])

# VII. Matrix 연산

* M1, M2 지정

In [82]:
M1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [83]:
print(M1)

[[2 4]
 [6 8]]


In [84]:
M2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [85]:
print(M2)

[[3 5]
 [7 9]]


>## 1) Matrix 곱

* M1 @ M2

In [86]:
M1.dot(M2)

array([[ 34,  46],
       [ 74, 102]])

* M2 @ M1

In [87]:
np.dot(M2, M1)

array([[ 36,  52],
       [ 68, 100]])

* Warning : M1 * M2 

In [88]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [89]:
M2 * M1

array([[ 6, 20],
       [42, 72]])

>## 2) 전치 행렬

* M1의 전치 행렬

In [90]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

* M2의 전치 행렬

In [91]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [92]:
M2.T

array([[3, 7],
       [5, 9]])

# 
# 
# 
# The End
# 
# 
# 