# 5. Getting Started with pandas

In [164]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt       # 그래프를 세부적으로 그리기 위한 옵션 설정
import matplotlib as mpl              # 한글폰트, 글씨체, 음수기호 등 전체적인 옵션 조정

import missingno as msno
%matplotlib inline      
# NoteBook 내에 그래프 그리기
# %matplotlib tk 는 별도의 창에 그래프를 그리고 직접 그래프의 속성을 변경할 수 있음

# 실수형 포맷
pd.options.display.float_format = '{:0,.2f}'.format 
np.random.seed(12345)

mpl.rc('font', family='NanumGothic')  # 한글 폰트 설정
                                        # 윈도우 폰트 위치 - C:\Windows\Fonts
mpl.rcParams['axes.unicode_minus'] = False

plt.figure(figsize=(10,5))              # 그래프 사이즈 설정
plt.rc('figure', figsize=(10, 6))

<Figure size 720x360 with 0 Axes>

In [4]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

## 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values (of
similar types to NumPy types) and an associated array of data labels, called its index

In [7]:
# Series 생성
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
# Series values 와 index 조회
obj.values, obj.index

(array([ 4,  7, -5,  3], dtype=int64), RangeIndex(start=0, stop=4, step=1))

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [13]:
# Compared with NumPy arrays, you can use labels in the index when selecting single
# values or a set of values:


obj2['a'], obj2[['c', 'a', 'd']]

(-5,
 c    3
 a   -5
 d    4
 dtype: int64)

In [16]:
obj2[obj2 > 0], obj2 * 2, np.exp(obj2)

(d    4
 b    7
 c    3
 dtype: int64,
 d     8
 b    14
 a   -10
 c     6
 dtype: int64,
 d      54.59815
 b   1,096.63316
 a       0.00674
 c      20.08554
 dtype: float64)

In [18]:
'b' in obj2, 'e' in obj2

(True, False)

In [22]:
# Should you have data contained in a Python dict, you can create a Series from it by
# passing the dict:

sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
  states = ['California', 'Ohio', 'Oregon', 'Texas']

  obj4 = pd.Series(data=sdata, index=states)
  obj4

California            NaN
Ohio         35,000.00000
Oregon       16,000.00000
Texas        71,000.00000
dtype: float64

In [27]:
# I will use the terms “missing” or “NA” interchangeably to refer to missing data. The
# isnull and notnull functions in pandas should be used to detect missing data:

pd.isnull(obj4), pd.notnull(obj4)


(California     True
 Ohio          False
 Oregon        False
 Texas         False
 dtype: bool,
 California    False
 Ohio           True
 Oregon         True
 Texas          True
 dtype: bool)

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
# A useful Series feature for many applications is that it automatically aligns by index
# label in arithmetic operations:

print(obj3)
print(obj4)
print(obj3 + obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California            NaN
Ohio         35,000.00000
Oregon       16,000.00000
Texas        71,000.00000
dtype: float64
California             NaN
Ohio          70,000.00000
Oregon        32,000.00000
Texas        142,000.00000
Utah                   NaN
dtype: float64


In [36]:
obj4.name = 'population'
obj4.index.name =  'state'
obj4

state
California            NaN
Ohio         35,000.00000
Oregon       16,000.00000
Texas        71,000.00000
Name: population, dtype: float64

In [37]:
# A Series’s index can be altered in-place by assignment:

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob','Steve','Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

A DataFrame represents a rectangular table of data and contains an ordered collec‐
tion of columns, each of which can be a different value type (numeric, string,
boolean, etc.).

In [40]:
# Dict를이용한 DataFrame 생성
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)
df

state  year     pop
0    Ohio  2000 1.50000
1    Ohio  2001 1.70000
2    Ohio  2002 3.60000
3  Nevada  2001 2.40000
4  Nevada  2002 2.90000
5  Nevada  2003 3.20000

In [41]:
df.head(), df.tail()

(    state  year     pop
 0    Ohio  2000 1.50000
 1    Ohio  2001 1.70000
 2    Ohio  2002 3.60000
 3  Nevada  2001 2.40000
 4  Nevada  2002 2.90000,
     state  year     pop
 1    Ohio  2001 1.70000
 2    Ohio  2002 3.60000
 3  Nevada  2001 2.40000
 4  Nevada  2002 2.90000
 5  Nevada  2003 3.20000)

In [43]:
# Dict data를 이용하여 DataFrame을 만들고 컬럼의 순서를 재조정
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state     pop
0  2000    Ohio 1.50000
1  2001    Ohio 1.70000
2  2002    Ohio 3.60000
3  2001  Nevada 2.40000
4  2002  Nevada 2.90000
5  2003  Nevada 3.20000

In [44]:
# If you pass a column that isn’t contained in the dict, it will appear with missing values
# in the result:

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

df2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])
df2

year   state     pop debt
one    2000    Ohio 1.50000  NaN
two    2001    Ohio 1.70000  NaN
three  2002    Ohio 3.60000  NaN
four   2001  Nevada 2.40000  NaN
five   2002  Nevada 2.90000  NaN
six    2003  Nevada 3.20000  NaN

In [45]:
# A column in a DataFrame can be retrieved as a Series either by dict-like notation or
# by attribute:

df2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [46]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [48]:
 df2.loc['three']

year       2002
state      Ohio
pop     3.60000
debt        NaN
Name: three, dtype: object

In [49]:
# Columns can be modified by assignment. For example, the empty 'debt' column
# could be assigned a scalar value or an array of values:

df2['debt'] = 16.5
df2

year   state     pop     debt
one    2000    Ohio 1.50000 16.50000
two    2001    Ohio 1.70000 16.50000
three  2002    Ohio 3.60000 16.50000
four   2001  Nevada 2.40000 16.50000
five   2002  Nevada 2.90000 16.50000
six    2003  Nevada 3.20000 16.50000

In [54]:
df2['debt'] = np.arange(6.)
df2

year   state     pop    debt
one    2000    Ohio 1.50000 0.00000
two    2001    Ohio 1.70000 1.00000
three  2002    Ohio 3.60000 2.00000
four   2001  Nevada 2.40000 3.00000
five   2002  Nevada 2.90000 4.00000
six    2003  Nevada 3.20000 5.00000

In [55]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.20000
four   -1.50000
five   -1.70000
dtype: float64

In [57]:
df2['debt'] = val # 인덱스가 동일한 경우 갱신, 인덱스가 없으면 NaN
df2

year   state     pop     debt
one    2000    Ohio 1.50000      NaN
two    2001    Ohio 1.70000 -1.20000
three  2002    Ohio 3.60000      NaN
four   2001  Nevada 2.40000 -1.50000
five   2002  Nevada 2.90000 -1.70000
six    2003  Nevada 3.20000      NaN

In [59]:
df2['eastern'] = df2.state == 'Ohio'
df2

year   state     pop     debt  eastern
one    2000    Ohio 1.50000      NaN     True
two    2001    Ohio 1.70000 -1.20000     True
three  2002    Ohio 3.60000      NaN     True
four   2001  Nevada 2.40000 -1.50000    False
five   2002  Nevada 2.90000 -1.70000    False
six    2003  Nevada 3.20000      NaN    False

In [60]:
# The del method can then be used to remove this column:
del df2['eastern']

In [62]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [64]:
# Another common form of data is a nested dict of dicts:
# If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys
# as the columns and the inner keys as the row indices:


pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

df3 = pd.DataFrame(pop)
df3

Nevada    Ohio
2001 2.40000 1.70000
2002 2.90000 3.60000
2000     NaN 1.50000

In [65]:
# You can transpose the DataFrame (swap rows and columns) with similar syntax to a
# NumPy array:

df3.T


2001    2002    2000
Nevada 2.40000 2.90000     NaN
Ohio   1.70000 3.60000 1.50000

In [66]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada    Ohio
2001 2.40000 1.70000
2002 2.90000 3.60000
2003     NaN     NaN

In [67]:
df3

Nevada    Ohio
2001 2.40000 1.70000
2002 2.90000 3.60000
2000     NaN 1.50000

In [68]:
# Dicts of Series are treated in much the same way:

pdata = {'Ohio': df3['Ohio'][:-1],
         'Nevada': df3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001 1.70000 2.40000
2002 3.60000 2.90000

In [69]:
 df3.index.name = 'year'
 df3.columns.name = 'state'
 df3

state  Nevada    Ohio
year                 
2001  2.40000 1.70000
2002  2.90000 3.60000
2000      NaN 1.50000

In [72]:
df3.sort_index(inplace=True)
df3

state  Nevada    Ohio
year                 
2000      NaN 1.50000
2001  2.40000 1.70000
2002  2.90000 3.60000

In [73]:
df3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [74]:
# If the DataFrame’s columns are different dtypes, the dtype of the values array will be
# chosen to accommodate all of the columns:

df2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [76]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, one to six
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   year    6 non-null      int64  
 1   state   6 non-null      object 
 2   pop     6 non-null      float64
 3   debt    3 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 412.0+ bytes


### Index Objects

In [5]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index, index[1:]

(Index(['a', 'b', 'c'], dtype='object'), Index(['b', 'c'], dtype='object'))

In [6]:
index[1] = 'd' # Type Error : Index does not support mutable operations

TypeError: Index does not support mutable operations

In [7]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [8]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.50000
1   -2.50000
2    0.00000
dtype: float64

In [ ]:
df3

## 5.2 Essential Functionality

### Reindexing

In [57]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.50000
b    7.20000
a   -5.30000
c    3.60000
dtype: float64

In [58]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.30000
b    7.20000
c    3.60000
d    4.50000
e        NaN
dtype: float64

In [59]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [60]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [61]:
# With DataFrame, reindex can alter either the (row) index, columns, or both. When
# passed only a sequence, it reindexes the rows in the result:

frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index = ['a','c','d'],
                     columns=['Ohio','Texas','California'])

frame2 = frame.reindex(['a','b','c','d'])
display('frame', 'frame2')


frame
   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

frame2
     Ohio   Texas  California
a 0.00000 1.00000     2.00000
b     NaN     NaN         NaN
c 3.00000 4.00000     5.00000
d 6.00000 7.00000     8.00000

In [11]:
# The columns can be reindexed with the columns keyword:

states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping Entries from an Axis - 행 또는 열 삭제하기 

In [66]:
# As we’ll explore in more detail, you can reindex more succinctly by label-indexing
# with loc, and many users prefer to use it exclusively:

frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index = ['a','c','d'],
                     columns=['Ohio','Texas','California'])

# frame.loc[['a', 'b', 'c', 'd'], states]
frame.loc[['a', 'c', 'd']]

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [43]:
# Series Data Drop

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj.drop(['e', 'd'])

a   0.00000
b   1.00000
dtype: float64

In [67]:
# With DataFrame, index values can be deleted from either axis. To illustrate this, we
# first create an example DataFrame:

# DataFrame 행(row, index) 삭제

df = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

df1 = df.drop(['Colorado', 'Ohio'])
display('df', 'df1')


df
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

df1
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [68]:
# DataFrame 열(columns) 삭제

df1 = df.drop('two', axis=1)
display('df', 'df1')

df
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

df1
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [69]:
# 원본 DataFrame 을 직접 변경 drop(, inplace=True)

df1 = df.copy()
df.drop('one', axis=1)
df1.drop('one', axis=1, inplace=True)
display('df', 'df1')

df
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

df1
          two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

### Indexing, Selection, and Filtering - 색인, 선택, 필터링

In [52]:
# Series 조회

obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
print(obj['b'])               # 'b'         - scala
print(obj[1])                 # 'b'         - scala
print(obj[2:4])               # 'c', 'd'    - Series
print(obj[['b', 'a', 'd']])   # 'b','a','d' - Series
print(obj[[1, 3]])            # 'b','d'     - Series
print(obj[obj < 2])           # 'a','b'     - Series

1.0
1.0
c   2.00000
d   3.00000
dtype: float64
b   1.00000
a   0.00000
d   3.00000
dtype: float64
b   1.00000
d   3.00000
dtype: float64
a   0.00000
b   1.00000
dtype: float64


In [54]:
# Slicing with labels behaves differently than normal Python slicing in that the end‐
# point is inclusive:

obj['b':'c']  # end-point inclusive


b   1.00000
c   2.00000
dtype: float64

In [56]:
# Setting using these methods modifies the corresponding section of the Series:

obj['b':'c'] = 5
obj

a   0.00000
b   5.00000
c   5.00000
d   3.00000
dtype: float64

In [8]:
# DataFrame 조회

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
print(data)
print('~'*40)
print(data['two'])
print('~'*40)
print(data[['three', 'one']])
print('~'*40)

# Indexing like this has a few special cases. First, slicing or selecting data with a boolean array:
print(data[:2])
print('~'*40)
print(data[data['three'] > 5])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


In [14]:
# The row selection syntax data[:2] is provided as a convenience. 
# Passing a single element or a list to the [] operator selects columns.

# Another use case is in indexing with a boolean DataFrame, such as one produced by a
# scalar comparison:

print(data)
print('~'*40)

print(data < 5)
print('~'*40)

data[data < 5] = 0
print(data)

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15


### Selection with loc and iloc - loc 와 iloc

For DataFrame label-indexing on the rows, I introduce the special indexing operators
loc and iloc. They enable you to select a subset of the rows and columns from a
DataFrame with NumPy-like notation using either axis labels (loc) or integers
(iloc).

In [31]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

print(data)
print('~'*40)

# As a preliminary example, let’s select a single row and multiple columns by label:
print(data.loc['Colorado', ['two','three']])
print('~'*40)

print(data.loc[['Colorado'], ['two','three']])
print('~'*40)

# We’ll then perform some similar selections with integers using iloc:
print(data.iloc[2, [3, 0, 1]])
print('~'*40)

print(data.iloc[2])
print('~'*40)

print(data.iloc[[1, 2], [3, 0, 1]])
print('~'*40)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
two      5
three    6
Name: Colorado, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          two  three
Colorado    5      6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
four    11
one      8
two      9
Name: Utah, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
one       8
two       9
three    10
four     11
Name: Utah, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          four  one  two
Colorado     7    4    5
Utah        11    8    9
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [40]:
# Both indexing functions work with slices in addition to single labels or lists of labels:

print(data)
print('~'*40)

print(data.loc[:'Utah', 'two'])
print('~'*40)

print(data.iloc[:, :3][data.three > 5])
print('~'*40)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


In [39]:
print(data.iloc[:, :3][data.three > 5])

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14


### Integer Indexes - 정수 색인

In [ ]:
# 인덱스가 정수일때 ser[-1] 에러 발생, but 인덱스가 정수가 아닌경우 마지막 값 출력
ser = pd.Series(np.arange(3.))
ser[-1] # Error Occure

ser2 = pd.Series(np.arange(3.0), index=['a','b','c'])
ser2[-1] # Non Error

In [47]:
ser2 = pd.Series(np.arange(3.0), index=['a','b','c'])
ser2
ser2[-1]

2.0

In [49]:
ser[:1]

0   0.00000
dtype: float64

In [50]:
ser.loc[:1]

0   0.00000
1   1.00000
dtype: float64

In [51]:
ser.iloc[:1]

0   0.00000
dtype: float64

### Arithmetic and Data Alignment - 산술연산과 데이터 정렬

In [52]:
 s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
 s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
print(s1)
print('~'*40)
print(s2)
print('~'*40)
print(s1+s2)


a    7.30000
c   -2.50000
d    3.40000
e    1.50000
dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a   -2.10000
c    3.60000
e   -1.50000
f    4.00000
g    3.10000
dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a   5.20000
c   1.10000
d       NaN
e   0.00000
f       NaN
g       NaN
dtype: float64


In [53]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df3 = df1 + df2
display('df1', 'df2', 'df3')

df1
               b       c       d
Ohio     0.00000 1.00000 2.00000
Texas    3.00000 4.00000 5.00000
Colorado 6.00000 7.00000 8.00000

df2
             b        d        e
Utah   0.00000  1.00000  2.00000
Ohio   3.00000  4.00000  5.00000
Texas  6.00000  7.00000  8.00000
Oregon 9.00000 10.00000 11.00000

df3
               b   c        d   e
Colorado     NaN NaN      NaN NaN
Ohio     3.00000 NaN  6.00000 NaN
Oregon       NaN NaN      NaN NaN
Texas    9.00000 NaN 12.00000 NaN
Utah         NaN NaN      NaN NaN

In [54]:
df1 = pd.DataFrame({'A':[1, 2]})
df2 = pd.DataFrame({'B':[3, 4]})

df1 + df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values - fill_value를 이용한 산술 방법

In arithmetic operations between differently indexed objects, you might want to fill
with a special value, like 0, when an axis label is found in one object but not the other:



In [55]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
display('df1','df2')

df1
        a       b        c        d
0 0.00000 1.00000  2.00000  3.00000
1 4.00000 5.00000  6.00000  7.00000
2 8.00000 9.00000 10.00000 11.00000

df2
         a        b        c        d        e
0  0.00000  1.00000  2.00000  3.00000  4.00000
1  5.00000      NaN  7.00000  8.00000  9.00000
2 10.00000 11.00000 12.00000 13.00000 14.00000
3 15.00000 16.00000 17.00000 18.00000 19.00000

In [56]:
df1 + df2

a        b        c        d   e
0  0.00000  2.00000  4.00000  6.00000 NaN
1  9.00000      NaN 13.00000 15.00000 NaN
2 18.00000 20.00000 22.00000 24.00000 NaN
3      NaN      NaN      NaN      NaN NaN

In [62]:
# Using the add method on df1, I pass df2 and an argument to fill_value:

print(df1.add(df2))
print('~'*40)
print(df1.add(df2, fill_value=0))

         a        b        c        d   e
0  0.00000  2.00000  4.00000  6.00000 NaN
1  9.00000      NaN 13.00000 15.00000 NaN
2 18.00000 20.00000 22.00000 24.00000 NaN
3      NaN      NaN      NaN      NaN NaN
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         a        b        c        d        e
0  0.00000  2.00000  4.00000  6.00000  4.00000
1  9.00000  5.00000 13.00000 15.00000  9.00000
2 18.00000 20.00000 22.00000 24.00000 14.00000
3 15.00000 16.00000 17.00000 18.00000 19.00000


In [68]:
print(1/df1)
print('~'*40)
print(df1.rdiv(1) )


        a       b       c       d
0     inf 1.00000 0.50000 0.33333
1 0.25000 0.20000 0.16667 0.14286
2 0.12500 0.11111 0.10000 0.09091
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        a       b       c       d
0     inf 1.00000 0.50000 0.33333
1 0.25000 0.20000 0.16667 0.14286
2 0.12500 0.11111 0.10000 0.09091


In [66]:
df1.rdiv(1)

a       b       c       d
0     inf 1.00000 0.50000 0.33333
1 0.25000 0.20000 0.16667 0.14286
2 0.12500 0.11111 0.10000 0.09091

In [71]:
# Relatedly, when reindexing a Series or DataFrame, you can also specify a different fill value:
    
df1.reindex(columns=df2.columns, fill_value=0)


a       b        c        d  e
0 0.00000 1.00000  2.00000  3.00000  0
1 4.00000 5.00000  6.00000  7.00000  0
2 8.00000 9.00000 10.00000 11.00000  0

In [73]:
print(df1)
print('~'*40)
print(df1.sub(1))
print('~'*40)
print(df1.rsub(1))

        a       b        c        d
0 0.00000 1.00000  2.00000  3.00000
1 4.00000 5.00000  6.00000  7.00000
2 8.00000 9.00000 10.00000 11.00000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         a       b       c        d
0 -1.00000 0.00000 1.00000  2.00000
1  3.00000 4.00000 5.00000  6.00000
2  7.00000 8.00000 9.00000 10.00000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         a        b        c         d
0  1.00000  0.00000 -1.00000  -2.00000
1 -3.00000 -4.00000 -5.00000  -6.00000
2 -7.00000 -8.00000 -9.00000 -10.00000


#### Operations between DataFrame and Series

In [78]:
arr = np.arange(12.).reshape((3, 4))

print(arr)
print('~'*40)

print(arr[0])
print('~'*40)

print(arr - arr[0])


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0. 1. 2. 3.]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [75]:
arr[0]

array([0., 1., 2., 3.])

In [76]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [82]:
# Index가 동일한 경우 산술 연산
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

print(frame)
print('~'*40)

print(series)
print('~'*40)

# By default, arithmetic between DataFrame and Series matches the index of the Series
# on the DataFrame’s columns, broadcasting down the rows:

print(frame - series)

             b        d        e
Utah   0.00000  1.00000  2.00000
Ohio   3.00000  4.00000  5.00000
Texas  6.00000  7.00000  8.00000
Oregon 9.00000 10.00000 11.00000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
b   0.00000
d   1.00000
e   2.00000
Name: Utah, dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             b       d       e
Utah   0.00000 0.00000 0.00000
Ohio   3.00000 3.00000 3.00000
Texas  6.00000 6.00000 6.00000
Oregon 9.00000 9.00000 9.00000


In [92]:
# If an index value is not found in either the DataFrame’s columns or the Series’s index,
# the objects will be reindexed to form the union:
    
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
print(frame)
print('~'*40)

print(series2)
print('~'*40)

print(frame + series2)

             b        d        e
Utah   0.00000  1.00000  2.00000
Ohio   3.00000  4.00000  5.00000
Texas  6.00000  7.00000  8.00000
Oregon 9.00000 10.00000 11.00000
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
b    0
e    1
f    2
dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             b   d        e   f
Utah   0.00000 NaN  3.00000 NaN
Ohio   3.00000 NaN  6.00000 NaN
Texas  6.00000 NaN  9.00000 NaN
Oregon 9.00000 NaN 12.00000 NaN


In [93]:
# If you want to instead broadcast over the columns, matching on the rows, you have to
# use one of the arithmetic methods. For example:

series3 = frame['d']

In [97]:
frame

b        d        e
Utah   0.00000  1.00000  2.00000
Ohio   3.00000  4.00000  5.00000
Texas  6.00000  7.00000  8.00000
Oregon 9.00000 10.00000 11.00000

In [94]:
series3

Utah      1.00000
Ohio      4.00000
Texas     7.00000
Oregon   10.00000
Name: d, dtype: float64

In [100]:
frame.sub(series3, axis='index')

b       d       e
Utah   -1.00000 0.00000 1.00000
Ohio   -1.00000 0.00000 1.00000
Texas  -1.00000 0.00000 1.00000
Oregon -1.00000 0.00000 1.00000

### Function Application and Mapping - 함수 적용과 매핑

NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [101]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
        index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622

In [102]:
np.abs(frame)

b       d       e
Utah   0.20471 0.47894 0.51944
Ohio   0.55573 1.96578 1.39341
Texas  0.09291 0.28175 0.76902
Oregon 1.24643 1.00719 1.29622

In [112]:
# Another frequent operation is applying a function on one-dimensional arrays to each
# column or row. DataFrame’s apply method does exactly this:

# Here the function f, which computes the difference between the maximum and 
# minimum of a Series, is invoked once on each column in frame. The result is a Series 
# having the columns of frame as its index

f = lambda x: x.max() - x.min()

print(frame)
print('~'*40)

frame1 = frame.apply(f, axis=0)
print(frame1)

              b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
b   1.80217
d   1.68403
e   2.68963
dtype: float64


In [113]:
# If you pass axis='columns' to apply, the function will be invoked once per row
# instead:
    
f = lambda x: x.max() - x.min()

print(frame)
print('~'*40)

frame1 = frame.apply(f, axis=1)
print(frame1)

              b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Utah     0.99838
Ohio     2.52151
Texas    0.67611
Oregon   2.54266
dtype: float64


In [115]:
frame

b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622

In [117]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

frame_1 = frame.apply(f)
frame_2 = frame.apply(f, axis='columns')

display('frame_1', 'frame_2')

frame_1
           b       d        e
min -0.55573 0.28175 -1.29622
max  1.24643 1.96578  1.39341

frame_2
            min     max
Utah   -0.51944 0.47894
Ohio   -0.55573 1.96578
Texas   0.09291 0.76902
Oregon -1.29622 1.24643

In [118]:
# 요소별 함수의 적용 
# applymap() - DataFrame 사용, map() - Series에서 사용

# Element-wise Python functions can be used, too. Suppose you wanted to compute a
# formatted string from each floating-point value in frame. You can do this with apply map:

format = lambda x: '%.2f' % x
frame1 = frame.applymap(format)
display('frame','frame1')

frame
              b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622

frame1
            b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [121]:
print(frame)
frame['e'].map(format)

              b       d        e
Utah   -0.20471 0.47894 -0.51944
Ohio   -0.55573 1.96578  1.39341
Texas   0.09291 0.28175  0.76902
Oregon  1.24643 1.00719 -1.29622


Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

### Sorting and Ranking - 정렬과 순위

In [123]:
# sort_index() - index를 기준으로 sort

obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print(obj)
obj.sort_index()

d    0
a    1
b    2
c    3
dtype: int64


a    1
b    2
c    3
d    0
dtype: int64

In [124]:
# With a DataFrame, you can sort by index on either axis:

df = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
df_1 = df.sort_index()
df_2 = df.sort_index(axis=1)
df_3 = df.sort_index(axis=1, ascending=False)
display('df','df_1','df_2','df_3')

df
       d  a  b  c
three  0  1  2  3
one    4  5  6  7

df_1
       d  a  b  c
one    4  5  6  7
three  0  1  2  3

df_2
       a  b  c  d
three  1  2  3  0
one    5  6  7  4

df_3
       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [125]:
# Series - sort_values()

obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.00000
5    2.00000
0    4.00000
2    7.00000
1        NaN
3        NaN
dtype: float64

In [130]:
# When sorting a DataFrame, you can use the data in one or more columns as the sort
# keys. To do so, pass one or more column names to the by option of sort_values:

frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame
frame_1 = frame.sort_values(by='b')


# To sort by multiple columns, pass a list of names:
frame_2 = frame.sort_values(by=['a','b'])


display('frame','frame_1','frame_2')


frame
   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

frame_1
   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

frame_2
   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

#### Ranking
**rank()** - ***특정변수를 기준으로 순위를 구함***

* 동점 처리 방법(tie-breaking methods)
1. 평균(method='average'), default
2. 최소값(method='min')
3. 최대값(method='max')
4. 첫번째값(method='first')
5. 조밀하게(method='dense')

In [140]:
# Ranking assigns ranks from one through the number of valid data points in an array.
# The rank methods for Series and DataFrame are the place to look; by default rank
# breaks ties by assigning each group the mean rank:

obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj)
print(obj.rank()) # default = average

# Ranks can also be assigned according to the order in which they’re observed in the data:
print(obj.rank(method='first'))

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64
0   6.50000
1   1.00000
2   6.50000
3   4.50000
4   3.00000
5   2.00000
6   4.50000
dtype: float64
0   6.00000
1   1.00000
2   7.00000
3   4.00000
4   3.00000
5   2.00000
6   5.00000
dtype: float64


In [151]:
# 높은 값일 수록 1순위 - rank()-ascending=False
# Assign tie values the maximum rank in the group

# print(obj.rank(ascending=False, method='max'))
print(obj.rank(ascending=False, method='min'))
print('~'*40)

print(obj.rank(ascending=False, method='dense'))

0   1.00000
1   7.00000
2   1.00000
3   3.00000
4   5.00000
5   6.00000
6   3.00000
dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0   1.00000
1   5.00000
2   1.00000
3   2.00000
4   3.00000
5   4.00000
6   2.00000
dtype: float64


In [149]:
# DataFrame can compute ranks over the rows or the columns:

frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame_1 = frame.rank()
frame_2 = frame.rank(axis='columns')

display('frame','frame_1', 'frame_2')

frame
         b  a        c
0  4.30000  0 -2.00000
1  7.00000  1  5.00000
2 -3.00000  0  8.00000
3  2.00000  1 -2.50000

frame_1
        b       a       c
0 3.00000 1.50000 2.00000
1 4.00000 3.50000 3.00000
2 1.00000 1.50000 4.00000
3 2.00000 3.50000 1.00000

frame_2
        b       a       c
0 3.00000 2.00000 1.00000
1 3.00000 1.00000 2.00000
2 1.00000 2.00000 3.00000
3 3.00000 2.00000 1.00000

### Axis Indexes with Duplicate Labels - 중복 레이블 색인

In [153]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [154]:
# The index’s is_unique property can tell you whether its labels are unique or not:

obj.index.is_unique # True or False

False

In [158]:
obj['a']

a    0
a    1
dtype: int64

In [160]:
obj['b']

b    2
b    3
dtype: int64

In [161]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0        1        2
a 0.27499  0.22891  1.35292
a 0.88643 -2.00164 -0.37184
b 1.66903 -0.43857 -0.53974
b 0.47699  3.24894 -1.02123

In [162]:
df.loc['b']

0        1        2
b 1.66903 -0.43857 -0.53974
b 0.47699  3.24894 -1.02123

## 5.3 Summarizing and Computing Descriptive Statistics - 기술 통계 계산과 요약

In [170]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
print(df)
print('~'*40)
print(df.sum())
print('~'*40)
print(df.sum(axis='columns'))
print('~'*40)

# NA values are excluded unless the entire slice (row or column in this case) is NA.
# This can be disabled with the skipna option:
print(df.mean(axis='columns'))
print(df.mean(axis='columns', skipna=False))

   one   two
a 1.40   NaN
b 7.10 -4.50
c  NaN   NaN
d 0.75 -1.30
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
one    9.25
two   -5.80
dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a    1.40
b    1.30
c     NaN
d   -0.28
dtype: float64
a     NaN
b    1.30
c     NaN
d   -0.28
dtype: float64


In [ ]:
# 최대값을 가지는 index 출력
# Series는 index, DataFrame은 index, columns
print(df.idxmax())
print('~'*40)
print(df.cumsum())

In [171]:
print(df.describe())

       one   two
count 3.00  2.00
mean  3.08 -2.90
std   3.49  2.26
min   0.75 -4.50
25%   1.07 -3.70
50%   1.40 -2.90
75%   4.25 -2.10
max   7.10 -1.30


In [173]:
# On non-numeric data, describe produces alternative summary statistics:

obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance - 상관관계와 공분산