In [1]:
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [2]:
np.ones(3)

array([1., 1., 1.])

In [6]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
size = (3, 4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1,5)

array([1, 2, 3, 4])

In [12]:
np.arange(1,5,2)

array([1, 3])

In [14]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2,3)
ndarr2

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
print(ndarr2)

[[0 1 2]
 [3 4 5]]


## 03) 데이터 타입

### 데이터 타입

In [23]:
arr = np.array([1,2,3], dtype=np.uint8)
arr
arr.dtype.kind       # data type 종류
arr.dtype.alignment
arr = arr.astype('int8') # data type 변경
arr.dtype

dtype('int8')

In [19]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [24]:
a = np.array([0, 255], dtype=np.uint8)
b = a.astype('int8')
print(a)
print(b) # int8


[  0 255]
[ 0 -1]


In [26]:
a16 = np.array( [1.333333], dtype=np.float16)
a32 = np.array( [1.333333], dtype=np.float32)
print(a16)
print(a32)

[1.333]
[1.333333]


In [27]:
a16 = np.array([ 1.0 ], dtype=np.float16)
a32 = np.array([ 1.0 ], dtype=np.float32)
print(a16/3)
print(a32/3)

[0.3333]
[0.33333334]


In [28]:
print(np.nan,  type(np.nan))
print(np.inf,  type(np.inf))
print(-np.inf,  type(-np.inf))

nan <class 'float'>
inf <class 'float'>
-inf <class 'float'>


In [29]:
arr = np.array([-1, 2, -3])
print(arr/0)

[-inf  inf -inf]


<ipython-input-29-cb6c03859f6d>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(arr/0)


In [30]:
arr = np.array([-1, 2, -3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


## 4) 인덱싱과 슬라이싱

### 인덱싱과 슬라이싱

In [33]:
arr = np.arange(4)
arr
arr[0]

0

In [37]:
arr = np.arange(4).reshape(2,2)
print(arr[0])
print(arr[0][0])
print(arr[0, 0])

[0 1]
0
0


In [39]:
# arr[0][0] 과 arr[0,0]의 처리 속도
# timeit 뒤에 나오는 코드를 1000만번을 7번 반복실행하고 걸린 시간의 평균을 반환

a = np.arange(10000).reshape(100,100)
%timeit a[0,50]

120 ns ± 2.92 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [40]:
a=np.arange(10000).reshape(100, 100)
%timeit a[0][50]

235 ns ± 4.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [42]:
arr = np.arange(4)
print(arr[:2])

[0 1]


In [43]:
arr = np.arange(4)
target = [ 0, 2 ]
print(arr[ target ])

[0 2]


In [49]:
arr = np.arange(5)
arr[[0,2]]

array([0, 2])

In [52]:
a=np.arange(16).reshape(4, 4)
a[[0,2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [53]:
arr = np.arange(20).reshape(4, 5)
print(arr[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [54]:
arr = np.arange(20).reshape(4, 5)
result = []
for row in arr:
    row_01 = [row[0], row[1]]
    result.append(row_01)

In [55]:
result

[[0, 1], [5, 6], [10, 11], [15, 16]]

In [57]:
arr[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [59]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
print(arr[ 1:4, 2:5])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [60]:
print(arr[1:, 2:])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## 05) 브로드캐스팅 

### 브로드캐스팅

In [5]:
import numpy as np
a = np.array( [ 1, 2, 3] )
b = np.array( [ 2, 3, 4] )
print( a + b )
print( a * b )
print( a % b )

[3 5 7]
[ 2  6 12]
[1 2 3]


In [6]:
# 스칼라(sclar) 연산은 전체 데이터에 확장 적용
print(a + 3)

[4 5 6]


In [7]:
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)

arr_diff = arr_high - arr_low
print(arr_diff)

[2700 1300  400 2200 1400]


In [8]:
arr_high_x3 = arr_high * 3
arr_low_x2 = arr_low * 2
print(arr_high_x3 + arr_low_x2)

[458100 459400 459700 467100 458700]


In [11]:
avg = (arr_high * 3 + arr_low * 2)
avg

array([458100, 459400, 459700, 467100, 458700])

In [12]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)
arr

array([[92700, 92400, 92100, 94300, 92300],
       [90000, 91100, 91700, 92100, 90900]])

In [16]:
arr[0]*3 + arr[1]*2

array([458100, 459400, 459700, 467100, 458700])

In [17]:
data = [
    [92700, 92400, 92100, 94300, 92300],
    [90000, 91100, 91700, 92100, 90900]
]
arr = np.array(data)

weight = np.array( [ 3, 2 ] ).reshape(2, 1)
print((weight * arr).sum(axis=0))

[458100 459400 459700 467100 458700]


## 06) 조건 연산

### 조건 연산

In [18]:
arr = np.array([10, 20, 30])
print(arr > 10)

[False  True  True]


In [19]:
arr = np.array([10,20,30])
cond = [False, True, True]
arr[cond]

array([20, 30])

In [20]:
arr = np.array([10, 20, 30])
cond = arr > 10
print(arr[ cond ])

[20 30]


In [21]:
# any() - 하나라도 참일 경우 참을 반환
# all() - 모두 참일 경우 참을 반환
print(cond.all())
print(cond.any())

False
True


In [22]:
# 파이썬의 기본 논리 연산자로 and, or, not이 있었다면 넘파이에서는 &, |, ~을 사용
arr = np.array([10, 20, 30])
cond0 = arr > 10
cond1 = arr < 30
print(arr[ cond0 & cond1 ])

[20]


In [23]:
arr = np.array([10, 20, 30])
print(arr[ (arr > 10) & (arr < 30) ])

[20]


In [25]:
arr = np.array([10, 20, 30])
cond = arr > 10
arr[cond] = 1
arr[~cond] = 0
print(arr)

[0 1 1]


In [26]:
arr = np.array([10, 20, 30])
arr = np.where( arr > 10, 1, 0)
print(arr)

[0 1 1]


In [27]:
# 만약 10보다 크다면 10을 더하고 그렇지 않다면 10을 빼고 싶은 경우
cond = arr > 10
arr[cond] = arr[cond] + 10
arr[~cond] = arr[~cond] -10

arr

array([-10,  -9,  -9])