# Tensor Manipulation

In [2]:
%matplotlib inline 
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pprint

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 15
matplotlib.rcParams['axes.unicode_minus'] = False

import warnings
warnings.filterwarnings('ignore')

Instructions for updating:
non-resource variables are not supported in the long term


## Simple Array

In [3]:
# https://www.tensorflow.org/api_guides/python/array_ops

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [8]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()
#tf.shape(t).eval()

array([4])

In [9]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2])

In [10]:

t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [13]:
t

<tf.Tensor 'Const_5:0' shape=(1, 2, 3, 4) dtype=int32>

In [12]:
t.eval()

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [ ]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

## Matmul Vs ultiply

In [16]:
matrix1 = tf.constant([[1., 2.], [3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

print('Metrix 1 shape', matrix1.shape)
print('Metrix 2 shape', matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 6.],
       [12.]], dtype=float32)

In [17]:
# Multiply
(matrix1*matrix2).eval()

array([[2., 4.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [22]:
# broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 1.]])
(matrix1+matrix2).eval()

array([[5., 4.]], dtype=float32)

In [23]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1+matrix2).eval()

Random values for variable initializations

In [ ]:

tf.random_normal([3]).eval()

In [ ]:
tf.random_uniform([2]).eval()

In [ ]:
tf.random_uniform([2, 3]).eval()

## Reduce Mean/Sum

In [ ]:
tf.reduce_mean([1, 2], axis=0).eval()

In [ ]:
x = [[1., 2.],
     [3., 4.]]


tf.reduce_mean(x).eval()

In [ ]:
tf.reduce_mean(x, axis=0).eval()

In [ ]:

tf.reduce_mean(x, axis=1).eval()

In [ ]:
tf.reduce_mean(x, axis=-1).eval()

In [ ]:
tf.reduce_sum(x).eval()