In [2]:
%matplotlib inline 
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 15
matplotlib.rcParams['axes.unicode_minus'] = False

import warnings
warnings.filterwarnings('ignore')

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
# Lab 4 Multi-variable linear regression
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2861.9668 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]]
1000 Cost:  1.1965659 
Prediction:
 [[152.6589 ]
 [183.80463]
 [181.09138]
 [196.70834]
 [140.44215]]
2000 Cost:  0.8012761 
Prediction:
 [[152.33366]
 [184.02872]
 [180.99315]
 [196.62613]
 [140.7457 ]]


In [11]:
for step in range(20001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.20714112 
Prediction:
 [[151.41556]
 [184.68959]
 [180.75014]
 [196.14113]
 [141.87689]]
100 Cost:  0.20711628 
Prediction:
 [[151.41573]
 [184.68953]
 [180.75024]
 [196.14085]
 [141.87709]]
200 Cost:  0.20708792 
Prediction:
 [[151.4159 ]
 [184.68945]
 [180.75034]
 [196.14056]
 [141.87729]]
300 Cost:  0.20705934 
Prediction:
 [[151.41603]
 [184.68938]
 [180.7504 ]
 [196.1403 ]
 [141.87749]]
400 Cost:  0.20703661 
Prediction:
 [[151.4162 ]
 [184.68933]
 [180.75052]
 [196.14003]
 [141.8777 ]]
500 Cost:  0.20700447 
Prediction:
 [[151.41635]
 [184.68925]
 [180.75058]
 [196.13976]
 [141.87788]]
600 Cost:  0.20698552 
Prediction:
 [[151.4165 ]
 [184.68921]
 [180.7507 ]
 [196.1395 ]
 [141.87811]]
700 Cost:  0.20695898 
Prediction:
 [[151.41664]
 [184.68912]
 [180.75076]
 [196.13922]
 [141.8783 ]]
800 Cost:  0.20693266 
Prediction:
 [[151.4168 ]
 [184.68906]
 [180.75085]
 [196.13893]
 [141.8785 ]]
900 Cost:  0.20690815 
Prediction:
 [[151.41693]
 [184.68898]
 [180.75093]
 [196.138