# Tensor Manipulation

In [1]:
%matplotlib inline 
import random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import pprint

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 15
matplotlib.rcParams['axes.unicode_minus'] = False

import warnings
warnings.filterwarnings('ignore')

Instructions for updating:
non-resource variables are not supported in the long term


## Simple Array

In [2]:
# https://www.tensorflow.org/api_guides/python/array_ops

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [3]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()
#tf.shape(t).eval()

array([4])

In [7]:
t = tf.constant([[1,2],
                 [3,4]])
tf.rank(t).eval(), tf.shape(t).eval()

(2, array([2, 2]))

In [17]:

t = tf.constant([[[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]]]])
print(tf.shape(t).eval())
print(t.eval())

[1 2 3 4]
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]


In [12]:
t.eval()

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [ ]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

## Matmul Vs ultiply

In [16]:
matrix1 = tf.constant([[1., 2.], 
                       [3., 3.]])
matrix2 = tf.constant([[2.],[2.]])

print('Metrix 1 shape', matrix1.shape)
print('Metrix 2 shape', matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 6.],
       [12.]], dtype=float32)

In [17]:
# Multiply
(matrix1*matrix2).eval()

array([[2., 4.],
       [6., 6.]], dtype=float32)

## Watch out broadcasting

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [22]:
# broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 1.]])
(matrix1+matrix2).eval()

array([[5., 4.]], dtype=float32)

In [23]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1+matrix2).eval()

Random values for variable initializations

In [18]:

tf.random_normal([3]).eval()


array([0.58597755, 0.55676264, 0.25931567], dtype=float32)

In [19]:
tf.random_uniform([2]).eval()

array([0.4934088, 0.7006384], dtype=float32)

In [20]:
tf.random_uniform([2, 3]).eval()

array([[0.43208718, 0.59306157, 0.289109  ],
       [0.05489087, 0.07509768, 0.6214081 ]], dtype=float32)

## Reduce Mean/Sum

In [29]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [36]:
x = [[1., 2.],
     [3., 4.]]


a = tf.reduce_mean(x, axis=1).eval()
a
tf.reduce_mean(a).eval()


2.5

In [37]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [38]:

tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [39]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [40]:
tf.reduce_sum(x).eval()

10.0

## Argmax

In [42]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval() 

array([1, 0, 0], dtype=int64)

In [43]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [44]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

## Reshape

In [47]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9,10,11]]])
t.shape

(2, 2, 3)

In [48]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
tf.reshape(t, shape=[-1,1,3]).eval()
#tf.reshape(t, shape=[-1,1,3]).shape

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

## Reshape(squeeze, expand)

In [56]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2])

In [57]:
tf.expand_dims([0,1,2], 1).eval()

array([[0],
       [1],
       [2]])

## One hot

In [58]:
tf.one_hot([[0],[1],[2],[0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [59]:
t = tf.one_hot([[0],[1],[2],[0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## Casting

In [61]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [62]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval()

array([1, 0, 1, 0])

## Stack

In [63]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

## Ones and Zeros like

In [67]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Zip

In [69]:
for x, y in zip([1,2,3], [4,5,6]):
    print(x, y)

1 4
2 5
3 6


In [70]:
for x, y, z in zip([1,2,3],[4,5,6,],[7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
